pipeline {
    
    agent any

    stages{
        stages('Dev'){
            steps{
                echo 'Hello World'
            }
        }
        stages('Test'){
            steps{
                echo 'Hello World'
            }
        }
        stages('OWASP'){
            steps{
                echo 'Hello World'
            }
        }
        stages('Prod'){
            steps{
                echo 'Hello World'
            }
        }
    }
}