apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: static-web
        image: lalbudha47/static-web-dashboard
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-web
spec:
  selector:
    app: static-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 31000  # Choose a port number in the allowed range (30000-32767)
      targetPort: 80
